/**
 * Public shop and person identifiers, in the browser (ADR-0006).
 *
 *     VYR-7K2M-4Q     a shop
 *     VYP-3H9T-8C     a person
 *
 * Pure. No fetch, no storage, no React.
 *
 * ## Why this is a third copy
 *
 * `vyora-api/src/identity/public-id.ts` and
 * `vyora-mobile/src/features/identity.ts` implement the same forty lines, and
 * so does this. The three repositories deliberately have no runtime dependency
 * on each other — the same reason the mobile app carries a copy rather than an
 * import. A shared package would need publishing, versioning, and keeping in
 * step with a phone binary that may be months old, to save an algorithm that
 * has not changed since ADR-0006.
 *
 * Drift is the real risk, and it is not left to discipline:
 * `tests/vyora/identity.test.ts` pins vectors **generated by the API's own
 * implementation**, so a change on any side that alters the encoding fails
 * here.
 *
 * ## The browser never mints an identifier
 *
 * There is no `generatePublicId` in this file. Uniqueness is a unique index in
 * PostgreSQL; a client that could mint its own would be naming something
 * nothing has agreed to.
 */

/** Crockford Base32 minus `Z`. No `I`, `L`, `O`, `U` — the read-aloud confusions. */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXY";
/** 31, prime. A power-of-two modulus cannot catch every substitution — ADR-0006. */
const MODULUS = ALPHABET.length;
const PAYLOAD_LENGTH = 5;

const VALUE = new Map<string, number>();
for (let i = 0; i < ALPHABET.length; i++) VALUE.set(ALPHABET[i]!, i);

export const ID_KINDS = { shop: "VYR", person: "VYP" } as const;
export type IdKind = keyof typeof ID_KINDS;

const PREFIX_TO_KIND = new Map<string, IdKind>(
  (Object.keys(ID_KINDS) as IdKind[]).map((kind) => [ID_KINDS[kind], kind])
);

/** Fold the confusions someone makes reading a code off a card, then strip separators. */
function normalise(input: string): string {
  return input
    .toUpperCase()
    .replace(/[IL]/g, "1")
    .replace(/O/g, "0")
    .replace(/[\s\-_]/g, "");
}

/** Weighted sum, modulo a prime. Weights are 1…5, one per payload position. */
function checkSymbolFor(payload: string): string {
  let sum = 0;
  for (let i = 0; i < payload.length; i++) {
    sum += VALUE.get(payload[i]!)! * (i + 1);
  }
  return ALPHABET[sum % MODULUS]!;
}

/** `VYR7K2M4Q` → `VYR-7K2M-4Q`. Grouped 4-2 so it can be read aloud in chunks. */
function format(kind: IdKind, body: string): string {
  return `${ID_KINDS[kind]}-${body.slice(0, 4)}-${body.slice(4)}`;
}

export type ParseFailure =
  "empty" | "unknown-prefix" | "wrong-length" | "invalid-character" | "checksum";

export type ParseResult =
  | { readonly ok: true; readonly kind: IdKind; readonly canonical: string }
  | { readonly ok: false; readonly reason: ParseFailure };

/**
 * Read an identifier someone typed or pasted.
 *
 * Case-insensitive, hyphen-optional, tolerant of the `I`/`L`/`O` confusions —
 * and never tolerant of a bad check symbol.
 */
export function parsePublicId(input: string, expected?: IdKind): ParseResult {
  if (!input || !input.trim()) return { ok: false, reason: "empty" };

  const text = normalise(input);
  const kind = PREFIX_TO_KIND.get(text.slice(0, 3));

  if (!kind || (expected && kind !== expected)) return { ok: false, reason: "unknown-prefix" };

  const body = text.slice(3);
  if (body.length !== PAYLOAD_LENGTH + 1) return { ok: false, reason: "wrong-length" };

  for (const symbol of body) {
    if (!VALUE.has(symbol)) return { ok: false, reason: "invalid-character" };
  }

  const payload = body.slice(0, PAYLOAD_LENGTH);
  if (body[PAYLOAD_LENGTH] !== checkSymbolFor(payload)) return { ok: false, reason: "checksum" };

  return { ok: true, kind, canonical: format(kind, body) };
}

/**
 * What a QR carries: the identifier, and nothing else.
 *
 * No name, address, pincode, phone, balance or token. A QR is photographed,
 * forwarded and printed, so everything inside it is public to everyone who will
 * ever see it.
 */
export function qrPayloadFor(canonical: string): string {
  const parsed = parsePublicId(canonical);
  if (!parsed.ok) {
    throw new Error(`Refusing to build a QR for an invalid identifier: ${parsed.reason}`);
  }
  return `vyora:${parsed.kind}/${parsed.canonical}`;
}

/** Read a scanned QR back. Anything that is not one of ours fails to parse. */
export function parseQrPayload(payload: string, expected?: IdKind): ParseResult {
  const match = /^vyora:(shop|person)\/(.+)$/i.exec(payload.trim());
  if (!match) return { ok: false, reason: "unknown-prefix" };

  const kind = match[1]!.toLowerCase() as IdKind;
  if (expected && kind !== expected) return { ok: false, reason: "unknown-prefix" };
  return parsePublicId(match[2]!, kind);
}

/**
 * What to tell the merchant when a typed code does not resolve.
 *
 * One message per failure, because they call for different actions and a
 * single "invalid code" would hide which.
 */
export function explainParseFailure(reason: ParseFailure, expected: IdKind = "shop"): string {
  const thing = expected === "shop" ? "shop" : "customer";
  switch (reason) {
    case "empty":
      return `Enter the ${thing} code to continue.`;
    case "unknown-prefix":
      return `That is not a Vyora ${thing} code. A ${thing} code starts with ${ID_KINDS[expected]}.`;
    case "wrong-length":
      return `A ${thing} code has six characters after ${ID_KINDS[expected]}, like ${ID_KINDS[expected]}-7K2M-4Q.`;
    case "invalid-character":
      return "That code contains a character Vyora codes never use. Check it and try again.";
    case "checksum":
      // Deliberately not "invalid": the code is well-formed, so the likeliest
      // cause is one mistyped character rather than the wrong code entirely.
      return "That code does not look right — one character is probably wrong. Check it and try again.";
  }
}
