export const siteConfig = {
  name: "Esytol",
  tagline: "Free online tools — one platform.",
  description:
    "Esytol is a free platform of online tools for developers, designers, writers, and everyday users. Fast, private, and always available.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://esytol.com",
  // Site-wide default OG image, generated by app/og/[slug]/route.tsx (branded,
  // no static PNG). Per-tool pages override this with /og/<slug>.
  ogImage: "/og/site",
  links: {
    github: "https://github.com/EasyTechLabs/esytol",
  },
  keywords: [
    "online tools",
    "free tools",
    "developer tools",
    "text tools",
    "converter",
    "formatter",
    "generator",
    "encoder",
    "esytol",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
