/**
 * The brand's own description of itself.
 *
 * Two rules, learned the hard way in PLATFORM-001:
 *
 * 1. **Describe the platform, not the category.** "Free online tools — one platform"
 *    leaves room for every future category; "India's finance calculators" would have
 *    to be rewritten the day a non-finance tool ships.
 * 2. **Never promise a category we do not have.** This block previously described
 *    tools "for developers, designers, writers" and carried keywords for developer,
 *    text, converter, formatter and encoder tools — none of which are live — while
 *    omitting finance, which is the only thing the site actually offers. Copy that
 *    oversells is the same failure as copy that undersells.
 *
 * Keywords are ordered platform-first, then the categories that genuinely exist. The
 * finance terms the site actually ranks for are preserved.
 */
export const siteConfig = {
  name: "Esytol",
  tagline: "Free online tools — one platform.",
  description:
    "Esytol is a free platform of online tools. Finance is our deepest category — EMI, SIP, tax, loans and retirement, built for India — alongside everyday utilities, with more categories on the way. Fast, private, no signup.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://esytol.com",
  // Site-wide default OG image, generated by app/og/[slug]/route.tsx (branded,
  // no static PNG). Per-tool pages override this with /og/<slug>.
  ogImage: "/og/site",
  keywords: [
    "online tools",
    "free tools",
    "free online tools",
    "calculator",
    "finance calculator",
    "emi calculator",
    "sip calculator",
    "income tax calculator",
    "india",
    "esytol",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
