/**
 * OPERATION-001 — the Monday run.
 *
 * One command executes the weekly operating cycle and writes the Executive Growth
 * Report to .forge/reports/. It builds NOTHING new: every number comes from the
 * existing engines (growth providers, marketing agent, SEO intelligence, link
 * audit, freshness module). Anything unreadable is written "unknown".
 *
 * Usage:   npx tsx scripts/weekly.mjs
 * Also run (separately, they need their own tools):
 *   forge execution production verify --url https://www.esytol.com ...
 *   forge doctor
 *
 * Exit code 1 while no analytics provider is live — the report still writes, but
 * the run is honest that the business is operating blind.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const load = (p) => import(pathToFileURL(join(root, p)).href);

const { buildContext, runAgents } = await load("lib/marketing-agent/index.ts");
const { buildWeeklyReport } = await load("lib/marketing-agent/reports/weekly.ts");
const { analyseSeo } = await load("lib/seo-intelligence/index.ts");
const { getArticleSlugs, getArticleBySlug } = await load("lib/learn.ts");
const { getLiveTools } = await load("registry/index.ts");

const now = new Date();
const ctx = await buildContext(now);
const { ranked } = runAgents(ctx);
const weekly = buildWeeklyReport(ctx, ranked);
const seo = analyseSeo(ctx);

// ── quality scans (real, local) ─────────────────────────────────────────────
const slugs = new Set(getArticleSlugs());
const toolSlugs = new Set(getLiveTools().map((t) => t.slug));
const articles = getArticleSlugs().map(getArticleBySlug);
let brokenLinks = 0;
for (const a of articles) {
  for (const m of a.body.matchAll(/\/learn\/([a-z0-9-]+)/g)) if (!slugs.has(m[1])) brokenLinks++;
  for (const m of a.body.matchAll(/\/tools\/([a-z0-9-]+)/g))
    if (!toolSlugs.has(m[1])) brokenLinks++;
}
const freshness = ranked.filter((r) => r.id.startsWith("content-freshness"));

// ── the report ──────────────────────────────────────────────────────────────
const iso = now.toISOString().slice(0, 10);
const anyLive = !ctx.growth.noneLive;
const u = "unknown — waiting for provider access";
const gsc = ctx.growth.searchConsole;
const ga = ctx.growth.analytics;
const num = (v, live) => (live ? new Intl.NumberFormat("en-IN").format(Math.round(v)) : u);
const ev = (name) => ga.data.events.find((e) => e.label === name)?.value;

const lines = [
  `# Executive Growth Report — week of ${iso}`,
  ``,
  `> Generated by \`scripts/weekly.mjs\` from the engines. Every figure is real or "${u.split(" — ")[0]}".`,
  ``,
  `## Provider status`,
  ...weekly.providerStatus.map((s) => `- ${s}`),
  ``,
  `## Search (28d)`,
  `- Impressions: ${num(gsc.data.totals.impressions, gsc.status === "live")}`,
  `- Clicks: ${num(gsc.data.totals.clicks, gsc.status === "live")}`,
  `- CTR: ${gsc.status === "live" ? (gsc.data.totals.ctr * 100).toFixed(1) + "%" : u}`,
  `- Avg position: ${gsc.status === "live" ? gsc.data.totals.position : u}`,
  ``,
  `## Behaviour (28d)`,
  `- Users: ${num(ga.data.totals.users, ga.status === "live")}`,
  `- Returning users: ${num(ga.data.totals.returningUsers, ga.status === "live")}`,
  `- Comparison views: ${ga.status === "live" ? (ev("comparison_view") ?? 0) : u}`,
  `- Comparison CTA clicks: ${ga.status === "live" ? (ev("comparison_cta_click") ?? 0) : u}`,
  ``,
  `## Winners / losers`,
  gsc.status === "live"
    ? [
        ...gsc.data.topQueries
          .filter((q) => q.positionDelta <= -1)
          .slice(0, 5)
          .map((q) => `- ▲ "${q.query}" (${q.positionDelta})`),
        ...gsc.data.topQueries
          .filter((q) => q.positionDelta >= 1)
          .slice(0, 5)
          .map((q) => `- ▼ "${q.query}" (+${q.positionDelta})`),
      ].join("\n") || "- no material movement"
    : `- ${u}`,
  ``,
  `## Quality scans (local, real)`,
  `- Broken internal links: ${brokenLinks}`,
  `- Freshness alerts: ${freshness.length}${freshness.length ? " — " + freshness.map((f) => f.page).join(", ") : ""}`,
  `- Articles: ${articles.length} · Live tools: ${toolSlugs.size}`,
  ``,
  `## Top recommendations (ranked, evidence-based)`,
  ...ranked
    .slice(0, 8)
    .map(
      (r, i) =>
        `${i + 1}. [${r.priority}] ${r.title} — ${r.reason.slice(0, 120)} (score ${r.score}, ${r.effort})`
    ),
  ``,
  `## Cluster coverage`,
  ...seo.clusters.map(
    (c) =>
      `- ${c.label}: ${c.tools} tools · ${c.articles} articles · ${Math.round(c.coverage * 100)}% coverage`
  ),
  ``,
  `## Manual checklist (run separately)`,
  `- [ ] forge execution production verify — PASS required`,
  `- [ ] forge doctor — deployment health + provider verdict on HEAD`,
  `- [ ] /admin returns 401 anonymously (security)`,
  ``,
  `_Blind-state note: ${anyLive ? "at least one provider is live." : "NO provider is live — the business is operating without user data. Gate 0 (OBSERVATION.md) remains the #1 action."}_`,
];

const dir = join(root, ".forge", "reports");
mkdirSync(dir, { recursive: true });
const file = join(dir, `${iso}-executive.md`);
writeFileSync(file, lines.flat().join("\n") + "\n", "utf8");
console.log(`report written: ${file}`);
console.log(anyLive ? "providers: some live" : "providers: ALL BLIND — Gate 0 pending");
process.exitCode = anyLive ? 0 : 1;
