/**
 * Vyora — public identifiers and QR payloads, in the browser.
 *
 * The interesting risk here is not "does the parser work" — it is **drift**.
 * `lib/vyora/identity.ts` is a deliberate copy of the API's
 * `src/identity/public-id.ts`, because these repositories have no runtime
 * dependency on each other. A copy that silently diverges produces a client
 * that rejects codes the server considers valid, months later, in the field.
 *
 * So the first block pins vectors that were **generated by running the API's
 * own implementation** — not computed by hand, and not produced by the module
 * under test. If either side changes the encoding, these fail.
 */

import { describe, expect, it } from "vitest";
import {
  ID_KINDS,
  explainParseFailure,
  parsePublicId,
  parseQrPayload,
  qrPayloadFor,
  type IdKind,
} from "@/lib/vyora/identity";

/**
 * Generated by `vyora-api/src/identity/public-id.ts` (`generatePublicId` with a
 * seeded PRNG, seed 12345). Regenerate only if ADR-0006 changes the encoding —
 * and if you regenerate these to make a test pass, the encoding changed and the
 * server has to change with it.
 */
const API_VECTORS: ReadonlyArray<{ kind: IdKind; id: string; qr: string }> = [
  { kind: "shop", id: "VYR-TPK9-S9", qr: "vyora:shop/VYR-TPK9-S9" },
  { kind: "person", id: "VYP-HVD2-6R", qr: "vyora:person/VYP-HVD2-6R" },
  { kind: "shop", id: "VYR-6WR3-0P", qr: "vyora:shop/VYR-6WR3-0P" },
  { kind: "person", id: "VYP-6Y88-PF", qr: "vyora:person/VYP-6Y88-PF" },
  { kind: "shop", id: "VYR-WMEN-3Q", qr: "vyora:shop/VYR-WMEN-3Q" },
  { kind: "person", id: "VYP-PTB7-55", qr: "vyora:person/VYP-PTB7-55" },
];

describe("agreement with the server's implementation", () => {
  it("accepts every identifier the API generated", () => {
    for (const vector of API_VECTORS) {
      const parsed = parsePublicId(vector.id);
      expect(parsed.ok, vector.id).toBe(true);
      if (!parsed.ok) continue;
      expect(parsed.kind).toBe(vector.kind);
      expect(parsed.canonical).toBe(vector.id);
    }
  });

  it("builds the same QR payload the API would", () => {
    for (const vector of API_VECTORS) {
      expect(qrPayloadFor(vector.id)).toBe(vector.qr);
      const back = parseQrPayload(vector.qr);
      expect(back.ok && back.canonical).toBe(vector.id);
    }
  });
});

describe("reading a code somebody typed", () => {
  it("forgives the confusions people actually make", () => {
    // `O` for zero, `I`/`L` for one, lowercase, missing hyphens, stray spaces.
    for (const typed of ["vyr-tpk9-s9", "vyrtpk9s9", " VYR TPK9 S9 ", "vyr_tpk9_s9"]) {
      const parsed = parsePublicId(typed, "shop");
      expect(parsed.ok, typed).toBe(true);
      expect(parsed.ok && parsed.canonical).toBe("VYR-TPK9-S9");
    }
  });

  it("refuses a well-formed code with a wrong check symbol", () => {
    // `TPK9S` checksums to `9`, so `…-S8` is one flipped character.
    const parsed = parsePublicId("VYR-TPK9-S8", "shop");
    expect(parsed.ok).toBe(false);
    expect(!parsed.ok && parsed.reason).toBe("checksum");
  });

  it("refuses a person code where a shop code belongs", () => {
    // Fails here, as a parse error, rather than travelling to the server and
    // coming back "not found".
    const parsed = parsePublicId("VYP-HVD2-6R", "shop");
    expect(parsed.ok).toBe(false);
    expect(!parsed.ok && parsed.reason).toBe("unknown-prefix");
  });

  it("refuses the letters the alphabet deliberately excludes", () => {
    // `Z` is out (ADR-0006), and `U` is out. Both would otherwise be plausible.
    for (const symbol of ["Z", "U"]) {
      expect(ID_KINDS.shop + symbol).toBeTruthy();
      const parsed = parsePublicId(`VYR-${symbol}PK9-S9`, "shop");
      expect(parsed.ok, symbol).toBe(false);
    }
  });
});

describe("what a QR carries", () => {
  it("is the identifier and nothing else", () => {
    // A QR is photographed, forwarded, printed and left on a counter. Every
    // byte in it is public to everyone who will ever see it, permanently.
    const payload = qrPayloadFor("VYR-TPK9-S9");
    expect(payload).toBe("vyora:shop/VYR-TPK9-S9");

    for (const forbidden of ["http", "@", "token", "bearer", "address", "pincode"]) {
      expect(payload.toLowerCase()).not.toContain(forbidden);
    }
  });

  it("refuses to build one for an identifier that does not parse", () => {
    expect(() => qrPayloadFor("VYR-TPK9-S8")).toThrow();
    expect(() => qrPayloadFor("")).toThrow();
  });

  it("does not read a payload that is not ours", () => {
    for (const other of ["upi://pay?pa=x@y", "https://example.com/VYR-TPK9-S9", "VYR-TPK9-S9"]) {
      expect(parseQrPayload(other, "shop").ok, other).toBe(false);
    }
  });
});

describe("what the merchant is told", () => {
  it("names the specific failure rather than saying 'invalid'", () => {
    // Each of these calls for a different action, and one message would hide
    // which. The camera in particular sees a great many things that are not
    // Vyora codes.
    const messages = new Set(
      (["empty", "unknown-prefix", "wrong-length", "invalid-character", "checksum"] as const).map(
        (reason) => explainParseFailure(reason, "shop")
      )
    );
    expect(messages.size).toBe(5);
    for (const message of messages) expect(message.toLowerCase()).not.toBe("invalid code");
  });
});
